"""K562 manuscript tables from a k562_rerun.py results TSV (final numbering).

Main text: Tables 2-6. Supplementary: Tables S1 (columns 2-3, WGS BIC-seq2 bins), S2-S15, S19, S20.
(Table 1: table1_wgs_callers.py. Table 7 and Supplementary Tables S16-S18: independent cell lines. Supplementary Table S1
columns 4-7 (Control-FREEC / CNVpytor profiles): profile_references.py. Supplementary Table S21: depth analysis.)

Run from paper/:
  python scripts/make_tables.py                                   # from expected/k562_MboI.tsv
  python scripts/make_tables.py --results output/k562/results_MboI.tsv --outdir output/tables/k562
Writes <outdir>/k562_tables.md (all tables) and one TSV per table (<outdir>/table2.tsv, tableS1.tsv, ...).
Matching: CNV call = segment with |log2| >= 0.3; matched = IoU > 0.5 with a reference call of the same direction.
All segment-level tables use BIC-seq2 at lambda = 3 unless stated.
"""
import argparse
import os

import pandas as pd

SIZES = ['< 1 Mb', '1-2 Mb', '2-5 Mb', '5-10 Mb', '10-20 Mb', '20-50 Mb', '>= 50 Mb']
SEG_COLS = ['PCC_bicseq2_l4', 'SCC_bicseq2_l4', 'iou50_calls', 'iou50_hits_trg', 'iou50_P', 'iou50_R']
SEG_NAMES = ['PCC', 'SCC', '# calls', '# matched', 'Precision', 'Recall']
CONS_COLS = ['SCC_bicseq2_l4', 'SCC_freec', 'SCC_cnvpytor']
CONS_NAMES = ['with BIC-seq2', 'with Control-FREEC', 'with CNVpytor']
FILTER_NAMES = {'mean': ('mean', 'Mean', 'w'), 'gaussian': ('Gaussian', 'Gaussian', 'w'), 'median': ('median', 'Median', 'w'),
                'savgol': ('Savitzky–Golay', 'Savitzky–Golay', 'w'), 'haar': ('Haar', 'Haar wavelet', 'L'), 'sym4': ('sym4', 'sym4 wavelet', 'L')}


def fmt(p):
    return str(int(p)) if float(p).is_integer() else str(p)


def cell(v):
    if isinstance(v, float):
        return f'{v:.3f}'
    return str(v)


class Writer:
    def __init__(self, outdir):
        self.outdir = outdir
        self.md = []

    def table(self, key, title, df, cols, names, note=None):
        out = pd.DataFrame({n: [cell(v) for v in df[c]] for c, n in zip(cols, names)})
        out.to_csv(os.path.join(self.outdir, f'{key}.tsv'), sep='\t', index=False)
        self._md(title, out, note)

    def size_table(self, key, title, blocks, label_name):
        """blocks: list of (block title or None, DataFrame with 'label', column name of 'a/b a/b ...' strata)."""
        rows = []
        for btitle, df, col in blocks:
            if btitle:
                rows.append([btitle] + [''] * len(SIZES))
            for _, r in df.iterrows():
                rows.append([r['label']] + r[col].split())
        out = pd.DataFrame(rows, columns=[label_name] + SIZES)
        out.to_csv(os.path.join(self.outdir, f'{key}.tsv'), sep='\t', index=False)
        self._md(title, out)

    def _md(self, title, out, note=None):
        lines = [f'**{title}**', '', '| ' + ' | '.join(out.columns) + ' |', '|' + '---|' * len(out.columns)]
        lines += ['| ' + ' | '.join(str(v) for v in r) + ' |' for r in out.itertuples(index=False)]
        if note:
            lines += ['', note]
        self.md.append('\n'.join(lines) + '\n')

    def write(self):
        path = os.path.join(self.outdir, 'k562_tables.md')
        with open(path, 'w') as f:
            f.write('# K562 tables (generated by scripts/make_tables.py)\n\n' + '\n'.join(self.md))
        return path


def ref_counts(df, col):
    """'Reference events (n)' row from the denominators of a recall-by-reference-size column."""
    return pd.DataFrame([{'label': 'Reference events (n)', col: ' '.join(x.split('/')[1] for x in df[col].iloc[0].split())}])


def with_label(df, labels):
    df = df.copy()
    df['label'] = labels
    return df


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--results', default='expected/k562_MboI.tsv', help='default: %(default)s')
    ap.add_argument('--outdir', default='output/tables/k562', help='default: %(default)s')
    args = ap.parse_args()
    os.makedirs(args.outdir, exist_ok=True)
    d = pd.read_csv(args.results, sep='\t')
    d['lam'] = d['lambda'].astype(float)
    bic = d[d.segmenter == 'bicseq2']
    b3 = bic[bic.lam == 3]
    W = Writer(args.outdir)

    base = b3[(b3.setting == 'complete') & (b3.method == 'none')]
    assert len(base) == 1, 'expected exactly one baseline row (complete, unsmoothed, lambda 3)'
    mean = b3[(b3.setting == 'complete') & (b3.method == 'mean')].sort_values('param')
    ctrl = b3[b3.setting == 'control'].sort_values('param')
    intra = b3[b3.setting == 'intra']
    comb = b3[b3.setting == 'combined'].sort_values('param')
    wl = [f'w = {fmt(p)}' for p in mean.param]

    # ---------------------------------------------------------------- residual smoothing (Table 2, S1-S3)
    t2 = with_label(pd.concat([base, mean]), ['HiNT-CNV reproduced'] + wl)
    s = with_label(t2, ['HiNT'] + wl)
    W.table('table2', 'Table 2. Segment-level performance of residual smoothing at λ = 3 (vs K562 WGS BIC-seq2 reference)',
            t2, ['label'] + SEG_COLS, ['Smoothing'] + SEG_NAMES)
    W.table('tableS1', 'Table S1 (columns 2-3). Normalization-level (bin-level) performance of residual smoothing vs WGS (BIC-seq2) bins',
            s, ['label', 'bin_PCC', 'bin_SCC'], ['Smoothing', 'PCC vs WGS (BIC-seq2)', 'SCC vs WGS (BIC-seq2)'],
            note='Columns 4-7 (Control-FREEC and CNVpytor profiles) are produced by scripts/profile_references.py.')
    W.size_table('tableS2', 'Table S2. Matched events by size for residual smoothing (λ = 3; K562 WGS BIC-seq2 reference)',
                 [('Matched reference events / reference events, by reference event size', pd.concat([ref_counts(s, 'iou50_recall_by_refsize'), s]), 'iou50_recall_by_refsize'),
                  ('Matched Hi-C calls / Hi-C calls, by call size', s, 'iou50_precision_by_callsize')], 'Smoothing')
    W.table('tableS3', 'Table S3. Consistency of residual smoothing against WGS-derived reference CNVs from BIC-seq2, Control-FREEC and CNVpytor (segment-level SCC)',
            s, ['label'] + CONS_COLS, ['Smoothing'] + CONS_NAMES)

    # ---------------------------------------------------------------- lambda x window grid (Table S4)
    un = bic[(bic.setting == 'complete') & (bic.method == 'none')].sort_values('lam')
    grid = [with_label(un, [f'unsmoothed, λ = {fmt(l)}' for l in un.lam])]
    for lam in (3, 2, 1, 0.5):
        g = bic[(bic.setting == 'complete') & (bic.method == 'mean') & (bic.lam == lam)].sort_values('param')
        grid.append(with_label(g, [f'mean w = {fmt(p)}, λ = {fmt(lam)}' for p in g.param]))
    W.table('tableS4', 'Table S4. Segmentation penalty (λ) sweep versus smoothing window on K562 (WGS BIC-seq2 reference)',
            pd.concat(grid), ['label'] + SEG_COLS, ['Setting', 'PCC', 'SCC', 'calls', 'matched', 'precision', 'recall'])

    # ---------------------------------------------------------------- smoothing methods (Table 3, S5, S6)
    filt = [with_label(base, ['unsmoothed'])]
    best = [with_label(base, ['HiNT-CNV reproduced'])]
    for meth, (short, long_, par) in FILTER_NAMES.items():
        g = b3[(b3.setting == 'complete') & (b3.method == meth)].sort_values('param')
        filt.append(with_label(g, [f'{short} ({par} = {fmt(p)})' for p in g.param]))
        top = g.loc[[g.SCC_bicseq2_l4.idxmax()]]
        best.append(with_label(top, [f'{long_} ({par} = {fmt(top.param.iloc[0])})']))
    filt = pd.concat(filt)
    W.table('table3', 'Table 3. Comparison of smoothing methods in K562 (λ = 3): parameter with the highest segment-level SCC per method',
            pd.concat(best), ['label', 'bin_PCC', 'bin_SCC'] + SEG_COLS,
            ['Method (parameter)', 'Bin PCC', 'Bin SCC'] + SEG_NAMES)
    W.table('tableS5', 'Table S5. Full smoothing-method comparison on K562 (λ = 3; WGS BIC-seq2 reference unless stated)',
            filt, ['label', 'bin_PCC', 'bin_SCC'] + SEG_COLS + ['SCC_freec', 'SCC_cnvpytor'],
            ['Method', 'bin PCC', 'bin SCC', 'PCC', 'SCC', 'calls', 'matched', 'P', 'R', 'SCC FREEC', 'SCC CNVpytor'])
    W.size_table('tableS6', 'Table S6. Matched reference events / reference events by reference event size for each smoothing method (λ = 3)',
                 [(None, pd.concat([ref_counts(filt, 'iou50_recall_by_refsize'), filt]), 'iou50_recall_by_refsize')], 'Method')

    # ---------------------------------------------------------------- control correction (Table 4, S7-S9)
    fl = [f'f = {float(p):.1f}' for p in ctrl.param]
    t4 = with_label(pd.concat([base, ctrl]), ['HiNT-CNV reproduced'] + fl)
    s = with_label(t4, ['HiNT'] + fl)
    W.table('table4', 'Table 4. Segment-level performance of control Hi-C residual correction (GM12878 control; λ = 3)',
            t4, ['label'] + SEG_COLS, ['Control fraction'] + SEG_NAMES)
    W.table('tableS7', 'Table S7. Normalization-level performance of control Hi-C residual correction',
            s, ['label', 'bin_PCC', 'bin_SCC'], ['Control correction', 'PCC', 'SCC'])
    W.size_table('tableS8', 'Table S8. Matched events by size for control Hi-C residual correction (λ = 3)',
                 [('Matched reference events / reference events, by reference event size', pd.concat([ref_counts(s, 'iou50_recall_by_refsize'), s]), 'iou50_recall_by_refsize'),
                  ('Matched Hi-C calls / Hi-C calls, by call size', s, 'iou50_precision_by_callsize')], 'Control correction')
    W.table('tableS9', 'Table S9. SCC consistency of control Hi-C residual correction against BIC-seq2, Control-FREEC and CNVpytor',
            s, ['label'] + CONS_COLS, ['Control correction'] + CONS_NAMES)

    # ---------------------------------------------------------------- complete vs intra-only (Table 5, S10-S12)
    iw = intra[intra.method == 'mean'].sort_values('param')
    m4 = mean[mean.param.isin([3, 5, 7, 9])]
    t5 = pd.concat([base, m4, intra[intra.method == 'none'], iw])
    t5 = with_label(t5, ['Complete Hi-C'] + [f'Complete Hi-C + smooth, w = {fmt(p)}' for p in m4.param]
                    + ['Intra-chromosomal-only Hi-C'] + [f'Intra-only Hi-C + smooth, w = {fmt(p)}' for p in iw.param])
    t5['time'] = ['~1 hour'] * (1 + len(m4)) + ['~6 min'] * (1 + len(iw))
    s = with_label(t5, ['inter + intra Hi-C'] + [f'inter + intra Hi-C + smooth, w = {fmt(p)}' for p in m4.param]
                   + ['intra Hi-C'] + [f'intra Hi-C + smooth, w = {fmt(p)}' for p in iw.param])
    W.table('table5', 'Table 5. Complete (intra + inter) versus intra-chromosomal-only Hi-C, alone and with residual smoothing (λ = 3)',
            t5, ['label'] + SEG_COLS + ['time'], ['Hi-C setting'] + SEG_NAMES + ['Parsing time'],
            note='Parsing time (single CPU core, 8 GB RAM) was measured once when building the coverage profiles; it is not recomputed here.')
    W.table('tableS10', 'Table S10. Normalization-level performance of complete versus intra-chromosomal-only Hi-C',
            s, ['label', 'bin_PCC', 'bin_SCC'], ['Hi-C setting', 'PCC', 'SCC'])
    W.size_table('tableS11', 'Table S11. Matched events by size for complete versus intra-chromosomal-only Hi-C (λ = 3)',
                 [('Matched reference events / reference events, by reference event size', pd.concat([ref_counts(s, 'iou50_recall_by_refsize'), s]), 'iou50_recall_by_refsize'),
                  ('Matched Hi-C calls / Hi-C calls, by call size', s, 'iou50_precision_by_callsize')], 'Hi-C setting')
    W.table('tableS12', 'Table S12. Consistency of complete versus intra-chromosomal-only Hi-C against BIC-seq2, Control-FREEC and CNVpytor',
            s, ['label'] + CONS_COLS, ['Hi-C setting'] + CONS_NAMES)

    # ---------------------------------------------------------------- combined (Table 6, S13-S15)
    c03 = ctrl[ctrl.param == 0.3]
    t6 = pd.concat([base, c03, m4, comb])
    t6 = with_label(t6, ['HiNT', 'f = 0.3'] + [f'w = {fmt(p)}' for p in m4.param] + [f'f = 0.3 + w = {fmt(p)}' for p in comb.param])
    W.table('table6', 'Table 6. Segment-level performance of combined control correction (f = 0.3) and residual smoothing (λ = 3)',
            t6, ['label'] + SEG_COLS, ['Correction'] + SEG_NAMES)
    W.table('tableS13', 'Table S13. Normalization-level performance of combined control correction and residual smoothing',
            t6, ['label', 'bin_PCC', 'bin_SCC'], ['Correction', 'PCC', 'SCC'])
    W.size_table('tableS14', 'Table S14. Matched events by size for combined control correction and residual smoothing (λ = 3)',
                 [('Matched reference events / reference events, by reference event size', pd.concat([ref_counts(t6, 'iou50_recall_by_refsize'), t6]), 'iou50_recall_by_refsize'),
                  ('Matched Hi-C calls / Hi-C calls, by call size', t6, 'iou50_precision_by_callsize')], 'Correction')
    W.table('tableS15', 'Table S15. Consistency of combined control correction and residual smoothing against WGS-derived references',
            t6, ['label'] + CONS_COLS, ['Correction'] + CONS_NAMES)

    # ---------------------------------------------------------------- CBS (Table S19)
    sl = ['unsmoothed'] + wl
    parts = [with_label(pd.concat([base, mean]), [f'BIC-seq2 (λ = 3): {x}' for x in sl])]
    for seg, name in (('cbs', 'CBS (default)'), ('cbs_sdundo', 'CBS (smooth.CNA + sdundo)')):
        c = d[(d.segmenter == seg) & (d.setting == 'complete')]
        c = pd.concat([c[c.method == 'none'], c[c.method == 'mean'].sort_values('param')])
        if len(c):
            parts.append(with_label(c, [f'{name}: ' + ('unsmoothed' if m == 'none' else f'w = {fmt(p)}') for m, p in zip(c.method, c.param)]))
    W.table('tableS19', 'Table S19. Alternative segmentation algorithm on K562: CBS (DNAcopy, α = 0.01; default, and smooth.CNA + undo.splits = "sdundo", undo.SD = 3) vs BIC-seq2 (λ = 3)',
            pd.concat(parts), ['label'] + CONS_COLS + SEG_COLS[2:],
            ['Segmenter: input', 'SCC BIC-seq2', 'SCC FREEC', 'SCC CNVpytor', 'calls', 'matched', 'precision', 'recall'])

    # ---------------------------------------------------------------- matching-rule sensitivity (Table S20)
    s = with_label(pd.concat([base, mean]), ['HiNT'] + wl)
    W.table('tableS20', 'Table S20. Sensitivity of precision (P) and recall (R) on K562 (λ = 3) to the matching rule and to the λ of the WGS BIC-seq2 reference',
            s, ['label', 'iou30_P', 'iou30_R', 'iou50_P', 'iou50_R', 'iou70_P', 'iou70_R', 'recip50_P', 'recip50_R',
                'bicseq2_l3_P', 'bicseq2_l3_R', 'bicseq2_l5_P', 'bicseq2_l5_R'],
            ['Smoothing', 'P IoU 0.3', 'R IoU 0.3', 'P IoU 0.5', 'R IoU 0.5', 'P IoU 0.7', 'R IoU 0.7', 'P recip.', 'R recip.',
             'P ref λ3', 'R ref λ3', 'P ref λ5', 'R ref λ5'],
            note='Precision counts distinct matched Hi-C calls and recall distinct matched reference calls; '
                 'at IoU > 0.3 one call can overlap several reference events.')

    print('wrote', W.write())


if __name__ == '__main__':
    main()
