library(mgcv)
inf <- "/Users/weihanc./Desktop/hic/HiNTcnv_OUTPUT/K562_combined_dataForRegression/regressionInfo_nonZeros_allchroms.txt"
sink("/Users/weihanc./Desktop/hic/HiNTcnv_OUTPUT/K562_combined_dataForRegression/K562_combined_GAMregression.log",append=T)
inf
sink()
data <- read.table(inf,sep="	",header=T)
data <- data.frame(data)
lm1 <- gam(rowsum ~ s(gcper) + s(mapscore) + s(cutSitesNumber),data=data, family=poisson(link=log))
sink("/Users/weihanc./Desktop/hic/HiNTcnv_OUTPUT/K562_combined_dataForRegression/K562_combined_GAMregression.log",append=T)
summary(lm1)
sink()
rs <- residuals.gam(lm1,type="working")
write.table(rs,file="/Users/weihanc./Desktop/hic/HiNTcnv_OUTPUT/K562_combined_dataForRegression/regressionInfo_nonZeros_allchroms_residuals.r",quote=F,row.names=F,col.names=F)
pdf("/Users/weihanc./Desktop/hic/HiNTcnv_OUTPUT/K562_combined_GAMPoisson.pdf")
par(mfrow=c(2,2))
plot(lm1)
dev.off()
pred <- predict.gam(lm1, type='term')
rs.dev = residuals.gam(lm1,type="deviance")
rs.peason <- residuals.gam(lm1,type="pearson")
gam.check()
