library(mgcv)
inf <- "/home/chentw98/hic/HiNTcnv_OUTPUT/K562_dataForRegression/regressionInfo_nonZeros_allchroms.txt"
sink("/home/chentw98/hic/HiNTcnv_OUTPUT/K562_dataForRegression/K562_GAMregression.log",append=T)
inf
sink()
data <- read.table(inf,sep="	",header=T)
data <- data.frame(data)
lm1 <- gam(rowsum ~ s(gcper) + s(mapscore) + s(cutSitesNumber),data=data, family=poisson(link=log))
sink("/home/chentw98/hic/HiNTcnv_OUTPUT/K562_dataForRegression/K562_GAMregression.log",append=T)
summary(lm1)
sink()
rs <- residuals.gam(lm1,type="working")
write.table(rs,file="/home/chentw98/hic/HiNTcnv_OUTPUT/K562_dataForRegression/regressionInfo_nonZeros_allchroms_residuals.r",quote=F,row.names=F,col.names=F)
pdf("/home/chentw98/hic/HiNTcnv_OUTPUT/K562_GAMPoisson.pdf")
par(mfrow=c(2,2))
plot(lm1)
dev.off()
